services:
  - type: web
    name: vntx
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_DEBUG
        value: "true"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:P5Cp1kPCG8OvcNf0benVhzEKdJ/rs5PwhBP6lN+qiCY=
      - key: APP_NAME
        value: VNTX
      - key: APP_URL
        value: https://vntx.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_DATABASE
        value: byv7ppsfnwzasbjkwbcs
      - key: DB_HOST
        value: byv7ppsfnwzasbjkwbcs-mysql.services.clever-cloud.com
      - key: DB_PASSWORD
        value: GmpQm5XFFcAPj7sYbPLo
      - key: DB_PORT
        value: "3306"
      - key: DB_USERNAME
        value: u4tg9kcsplweszlg
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
